### ISSUE TITLE
[bug] improper host:port parsing for IPv6?

### ISSUE THREAD

**Issue by quillaja** [gorilla/reverse#5]
I noticed this function referenced elsewhere (stackoverflow) and the part (line 243) where you remove the port caught my eye. Won't that break for IPv6, which uses colons throughout? Would you not be better off using [`net.SplitHostPort()`](https://golang.org/pkg/net/#SplitHostPort)?

https://github.com/gorilla/reverse/blob/446ebc2d698ba830cf620a0d5c3039557b9811fc/matchers.go#L238-L249

**Comment by elithrar** [comment]
SplitHostPort requires a port, and fails without one.

You’re correct in that IPv6 isn’t covered here, however this library is
minimally maintained.
